### ISSUE TITLE
I try to execute LSC command

### ISSUE THREAD

**Issue by devesop** [a-rey/google_RAT#2]
It give a bug error:
lsc
Traceback (most recent call last):                  File "master.py", line 234, in <module>
    srv.server_list_clients()                       File "master.py", line 149, in server_list_clients                                                    info = base64.b64decode(raw_info.encode('UTF-8')).decode('UTF-8').split('|')                    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1: invalid continuation byte

**Comment by a-rey** [comment]
This looks like a Unicode decode error. The tool expects [UTF-8](https://en.wikipedia.org/wiki/UTF-8) formatted data. Are you running the clients on machines using a different encoding?

**Comment by devesop** [comment]
But what is the reason I try to test my url it show me a error. I mentioned in first issues

**Comment by devesop** [comment]
I really like your project. But I don't use that. Help me

**Comment by a-rey** [comment]
closing in reference to https://github.com/a-rey/google_RAT/issues/5
