### ISSUE TITLE
I execute test.py script

### ISSUE THREAD

**Issue by devesop** [a-rey/google_RAT#3]
!DOCTYPE html>
 2 html lang=en>
 3  <meta charset=utf-8>
 4  <meta name=viewport content="initial-scale=1,
 5  <title>Error 413 (Request Entity Too Large)!!1
 6  <style>
*{margin:0;padding:0}html,code{font:15p
 8    x/22px arial,sans-serif}html{background:#fff
 9  </style>
10  <a href=//www.google.com/><span id=logo aria-l
11  <p><b>413.</b> <ins>That’s an error.</ins>
12  <p>Your client issued a request that was
13  too large.
14 <script>
15  (function() { /*
16
17 Copyright The Closure Library Authors.
18 SPDX-License-Identifier: Apache-2.0
19 /
20 ar c=function(a,d,b){a=a+"=deleted; path="+d;nu
21 &&setTimeout(function(){if(history.replaceState
22
23 /script>
24 <ins>That’s all we know.</ins>

Traceback (most recent call last):
  File "test.py", line 39, in <module>
    assert(old_info[0] == uuid)
AssertionError

**Comment by a-rey** [comment]
Not a lot of info to go on here to help. This looks similar to [the other issue](https://github.com/a-rey/google_RAT/issues/2) you posted, but without the Unicode decoding error. Try using [this](https://abctool.gitlab.io/encoding-detector/) to figure out what encoding your data is using?

**Comment by devesop** [comment]
I am really sorry to ask this. I don't get it what are saying. could you please give the details

**Comment by devesop** [comment]
But unicode error I don't change any code inside the script. I just try what you said. But why iam getting this error.

**Comment by a-rey** [comment]
Post the command line you are using to run `test.py` so I can test locally.

**Comment by devesop** [comment]
Please update more like this project. Small help to fix the issues.

**Comment by a-rey** [comment]
closing in reference to https://github.com/a-rey/google_RAT/issues/5
