### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by IdanBanani** [a-rey/google_RAT#6]
This step isn't possible anymore (doesn't appear in the gui)
Review Permissions > Select your fake account > Advanced > Go to Untitled project (unsafe) > Allow

so once deployed as a web app- the web page said: script function wasn't found.

[Were I suppose to leave some parts from the template on the google script page?
```
function myFunction() {
  
}

```   

By the way - For those who try running it - Use a separate browsing profile ,otherwise it will keep reverting to your default google account

**Comment by a-rey** [comment]
Thank you for this! The GoogleAppsScript UI has changed. I updated the [README](https://github.com/a-rey/google_RAT/blob/master/README.md) to include these new changes. I was able to make a new app and test it using [`test.py`](https://github.com/a-rey/google_RAT/blob/master/client/test.py) with the new UI from Google.

Generally, the only undocumented gotcha is that you need to be using a private browser session when creating the fake Google account to prevent session cookies from another google account you are signed into from being used for app authentication when deploying your C2 server.
